# Generated by Django 3.1.2 on 2021-02-04 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.timestampedmodel')),
                ('name', models.CharField(default='', max_length=50)),
                ('ip', models.GenericIPAddressField(protocol='IPv4')),
                ('port_num', models.IntegerField()),
                ('administrator', models.CharField(default='', max_length=20)),
                ('device_select', models.CharField(choices=[('ups', 'UPS'), ('th', '온습도'), ('con', '접점')], max_length=3)),
            ],
            bases=('core.timestampedmodel',),
        ),
    ]
