# Generated by Django 3.1.6 on 2021-02-25 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_auto_20210225_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone_number',
            name='name_1',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='phone_number',
            name='name_10',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='phone_number',
            name='name_2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='phone_number',
            name='name_3',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='phone_number',
            name='name_4',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='phone_number',
            name='name_5',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='phone_number',
            name='name_6',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='phone_number',
            name='name_7',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='phone_number',
            name='name_8',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='phone_number',
            name='name_9',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='phone_number',
            name='phone_1',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='phone_number',
            name='phone_10',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='phone_number',
            name='phone_2',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='phone_number',
            name='phone_3',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='phone_number',
            name='phone_4',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='phone_number',
            name='phone_5',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='phone_number',
            name='phone_6',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='phone_number',
            name='phone_7',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='phone_number',
            name='phone_8',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='phone_number',
            name='phone_9',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
